/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Cem Gürbüz (https://sketchfab.com/cemgurbuzz)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/nvidia-geforce-rtx-3090-9b7cd73fefd5435f99f891567f5a9c2e
Title: Nvidia GeForce RTX 3090
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/rtx3090.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group position={[127.5, 88.512, 10.288]} rotation={[Math.PI / 2, 0.05, 0]} scale={0.304}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Fan_F_Black_Fan_0.geometry}
            material={materials.Black_Fan}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Fan_F_Slot1_0.geometry}
            material={materials['Slot.1']}
          />
        </group>
        <group
          position={[-123.897, 88.512, -37.824]}
          rotation={[Math.PI / 2, -0.05, Math.PI]}
          scale={0.304}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Fan_B_Black_Fan_0.geometry}
            material={materials.Black_Fan}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Fan_B_Slot1_0.geometry}
            material={materials['Slot.1']}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Metal_Frame_Metal_0.geometry}
          material={materials.Metal}
          position={[-0.001, 88.305, -8.473]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Front_Cover_Black_0.geometry}
          material={materials.Black}
          position={[-122.303, 89.693, 12.112]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[1, 1, 0.836]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Fan_Circle_Black_Fan_0.geometry}
          material={materials.Black_Fan}
          position={[127.5, 88.512, 10.288]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.794}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Front_Cover_U_Black_0.geometry}
          material={materials.Black}
          position={[0.021, 26.082, 14.089]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Front_Cover_T_Black_0.geometry}
          material={materials.Black}
          position={[-4.752, 163.401, 14.089]}
          rotation={[-Math.PI / 2, 0, -Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Fan_Circle_B_Black_Fan_0.geometry}
          material={materials.Black_Fan}
          position={[-124.154, 88.512, -40.178]}
          rotation={[Math.PI / 2, 0, Math.PI]}
          scale={0.794}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Grills_U_Metal_Black_0.geometry}
          material={materials.Metal_Black}
          position={[-0.119, 3.157, 3.087]}
          rotation={[Math.PI / 2, -Math.PI / 4, 0]}
          scale={[0.547, 11.753, 0.547]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Grills_T_Metal_Black_0.geometry}
          material={materials.Metal_Black}
          position={[0.798, 174.492, 3.087]}
          rotation={[-Math.PI / 2, Math.PI / 4, -Math.PI]}
          scale={[0.547, 11.753, 0.547]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane010_Black001_0.geometry}
          material={materials['Black.001']}
          position={[121.838, 88.416, -34.24]}
          rotation={[-Math.PI / 2, 0, -Math.PI]}
          scale={[1, 1, 0.836]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Socket_Slot_0.geometry}
          material={materials.Slot}
          position={[-149.707, 187.465, -39.009]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[1, 1.929, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Side_Metal_Part_Metal_S_0.geometry}
          material={materials.Metal_S}
          position={[-225.871, 118.087, -12.542]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Grills_F003_Metal_Black_0.geometry}
          material={materials.Metal_Black}
          position={[131.494, 88.839, -23.017]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[1, 1, 1.023]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Grills_F002_Metal_Black_0.geometry}
          material={materials.Metal_Black}
          position={[-128.175, 88.839, -4.172]}
          rotation={[Math.PI / 2, 0, Math.PI]}
          scale={[1, 0.97, 1.023]}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/rtx3090.glb')
